/*
 * Copyright (C) 2018,米珈科技有限公司 All rights reserved.
 * Project：ZMT
 * Author：马靖乘
 * Date：18-11-22 下午2:58
 */

package com.tonghechuanmei.android.model

/**
 * 我的粉丝
 */
data class FansListModel(
        var `data`: Data,
        var msg: String,
        var success: Boolean
) {
    data class Data(
            var pageInfo: PageInfo,
            var resultList: List<Result>
    ) {
        data class PageInfo(
                var address: Any,
                var age: Any,
                var alipayName: Any,
                var alipayNo: Any,
                var allContributeNum: Any,
                var allcount: Int,
                var allpage: Int,
                var appletOpenid: Any,
                var bankCardNo: Any,
                var bankOfDeposit: Any,
                var beanNum: Any,
                var birthday: Any,
                var cardholder: Any,
                var createTime: Any,
                var dateType: Any,
                var email: Any,
                var getuiCid: Any,
                var headImg: Any,
                var id: String,
                var integralUsed: Int,
                var isSupplier: Any,
                var keyword: Any,
                var lat: Any,
                var lng: Any,
                var memberId: Any,
                var memberLevelId: Any,
                var memberLevelLogo: Any,
                var name: Any,
                var nickName: Any,
                var noRecorded: Any,
                var orderby: Any,
                var page: Int,
                var phone: Any,
                var phoneType: Any,
                var postcode: Any,
                var qq: Any,
                var qqOpenid: Any,
                var qqUid: Any,
                var refereeUserId: Any,
                var refereeUserNum: Any,
                var remark: Any,
                var rows: Int,
                var searchName: Any,
                var serverArea: Any,
                var serverAreaId: Any,
                var sex: Any,
                var shanghejiaId: Any,
                var sort: Any,
                var start: Int,
                var state: Any,
                var statisticsDate: Any,
                var statisticsDateEnd: Any,
                var statisticsDateStart: Any,
                var statisticsMonth: Any,
                var surplusIncome: Any,
                var todayContributeNum: Any,
                var totalIncome: Long,
                var userLink: Any,
                var uuid: Any,
                var weixinNo: Any,
                var weixinOpenid: Any,
                var weixinUid: Any,
                var weixinUnionid: Any,
                var xinlangOpenid: Any,
                var xinlangUid: Any
        )

        data class Result(
            var address: String,
            var age: Int,
            var alipayName: Any,
            var alipayNo: Any,
            var allContributeNum: Any,
            var appletOpenid: Any,
            var bankCardNo: Any,
            var bankOfDeposit: Any,
            var beanNum: String,
            var birthday: Any,
            var cardholder: Any,
            var createTime: Long,
            var email: String,
            var getuiCid: Any,
            var headImg: String,
            var id: String,
            var identification: Any,
            var isBind: Any,
            var isSupplier: String,
            var keyword: Any,
            var lat: Any,
            var lng: Any,
            var memberId: String,
            var memberLevelId: Any,
            var memberLevelLogo: Any,
            var name: String,
            var nickName: String,
            var noRecorded: Any,
            var phone: String,
            var phoneType: Any,
            var postcode: Any,
            var pwd: String,
            var qq: String,
            var qqOpenid: Any,
            var qqUid: Any,
            var refereeUserId: String,
            var refereeUserName: Any,
            var refereeUserNum: Any,
            var referrerUserCount: Int,
            var remark: String,
            var serverArea: Any,
            var serverAreaId: Any,
            var serverAreaName: Any,
            var sex: String,
            var shanghejiaId: Any,
            var sort: Int,
            var state: String,
            var surplusIncome: Int,
            var todayContributeNum: Any,
            var totalIncome: Long,
            var userLink: String,
            var uuid: Any,
            var weixinNo: String,
            var weixinOpenid: Any,
            var weixinUid: Any,
            var weixinUnionid: Any,
            var xinlangOpenid: String,
            var xinlangUid: Any
        )
    }
}